schema_version: "1.0"
mcp_name: "Rwandan Law MCP"
jurisdiction: "RW"

sources:
  - name: "Official Gazette of Rwanda"
    authority: "Official Gazette of Rwanda"
    official_portal: "https://www.minijust.gov.rw"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "weekly"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "Government Open Data"
      url: "https://www.minijust.gov.rw"
      summary: "Official legislative texts are public domain"
    coverage:
      scope: "Data protection, cybersecurity, e-commerce, criminal law cyber provisions"
      limitations: "AI-generated seed data; full official ingestion pending"
    languages:
      - "en"
      - "rw"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
